### ISSUE TITLE
Cách build release android apk

### ISSUE THREAD

**Issue by longb1997** [hngocl/BoilerplateReactNative#12]
Phiền bác cho em hỏi cách build release apk ở ver mới nhất ạ, em cám ơn

**Comment by ngocle2497** [comment]
Làm theo docs trên RN thôi bác

**Comment by longb1997** [comment]
Cứ chạy ./gradlew assembleRelease thôi hả bác? Em thấy mấy ver trước có command kiểu chỉ định file ENV:
ENVFILE=env/.dev && cd android && ./gradlew clean && yarn apk
