### ISSUE TITLE
bên android lấy deviceH nó không chính xác ạ 

### ISSUE THREAD

**Issue by thanhnvpk01168** [hngocl/BoilerplateReactNative#17]
<img width="1371" alt="Screen Shot 2022-07-31 at 12 46 35 PM" src="https://user-images.githubusercontent.com/58645779/182012156-ac362719-ff2a-4773-96bf-4324f17a200b.png">

**Comment by ngocle2497** [comment]
Nó lấy là cả cái navigation bar nha

**Comment by thanhnvpk01168** [comment]
@MasonLe2497 có cách nào lấy chính xác navigation bar ko a
<img width="1326" alt="Screen Shot 2022-07-31 at 10 32 40 PM" src="https://user-images.githubusercontent.com/58645779/182033798-9855c6a3-cdd7-4643-a1bc-f70e79628880.png">

**Comment by ngocle2497** [comment]
Dimension window
