### ISSUE TITLE
Cấu hình thêm 1 env

### ISSUE THREAD

**Issue by mocmoc05** [hngocl/BoilerplateReactNative#21]
Bác cho em hỏi về việc thêm 1 env cho ứng dụng với ạ. Hiện tại em đang thấy default đang có dev và prod, nếu bổ sung thêm env staging chẳng hạn thì sẽ chạy script như nào để tạo thêm ạ? hay là phải cấu hình manual phần này ạ.
Em cảm ơn nhiều.

**Comment by longb1997** [comment]
Bạn làm theo docs của react-native-config là được
