### ISSUE TITLE
error while running on android

### ISSUE THREAD

**Issue by NadeemKhanPl** [hngocl/BoilerplateReactNative#24]
yarn android:dev
yarn run v1.22.19
$ node ./scripts/android.js env/.dev devDebug
{
  envJson: {
    APP_ENV: 'Dev',
    API_URL: 'https:/',
    APP_DISPLAY_NAME: 'MyApp2-Dev',
    APP_PLACEHOLDER_NAME: 'MyApp2',
    VERSION_CODE: '1',
    VERSION_NAME: '1.0.0',
    BUNDLE_IDENTIFIER: 'com.myapp2',
    ASSETCATALOG_COMPILER_APPICON_NAME: 'AppIcon-Dev',
    DEBUG_PROVISIONING_PROFILE: 'com_myapp2',
    RELEASE_PROVISIONING_PROFILE: 'com_myapp2_appstore',
    DEFAULT_FALLBACK_LNG_I18n: 'en',
    '': '',
    '# Androi': '# Android',
    ANDROID_KESTORE_FILE: 'my-upload-key.keystore',
    ANDROID_KESTORE_PASSWORD: '111111',
    ANDROID_KESTORE_KEY_ALIAS: 'my-key-alias',
    ANDROID_KESTORE_KEY_PASSWORD: '111111'
  }
}
Old App not found
Done in 0.12s.

**Comment by ngocle2497** [comment]
what the error??

**Comment by NadeemKhanPl** [comment]
Old App not found this is the error

**Comment by ngocle2497** [comment]
No. :d . When u run android, by default old app of your project will be uninstall, then reinstall. I want to keep app cleanest when run command. It just a message log
