### ISSUE TITLE
How do I contribute in this ??

### ISSUE THREAD

**Issue by Vimal1464** [hngocl/BoilerplateReactNative#32]
I am really excited to contribute in this project as I am also a frontend react native developer kindly tell

**Comment by ngocle2497** [comment]
Just create PR

**Comment by Vimal1464** [comment]
@masonle2x2 oak

**Comment by Vimal1464** [comment]
@masonle2x2 
I am unable to start the project getting build error
kindly tell the step to start this.

**Comment by ngocle2497** [comment]
@Vimal1464 now u can check new document to contribute, thanks
