### ISSUE TITLE
Error code 127 exist right after setup project with cli

### ISSUE THREAD

**Issue by kentdev92** [hngocl/BoilerplateReactNative#35]
[https://user-images.githubusercontent.com/51183188/229588366-c8fbe3da-85b7-450d-a2a5-dff87cf5ffe0.png](https://user-images.githubusercontent.com/51183188/229588366-c8fbe3da-85b7-450d-a2a5-dff87cf5ffe0.png)
How can i fix this?

**Comment by kentdev92** [comment]
<img width="1242" alt="Screenshot 2024-04-18 at 17 21 02" src="https://github.com/ngocle2497/BoilerplateReactNative/assets/17426288/3c1fb45e-e50a-4fc1-a128-8d4a3369c97b">

**Comment by ngocle2497** [comment]
scroll down, you see node command not found?

**Comment by kentdev92** [comment]
<img width="725" alt="Screenshot 2024-04-18 at 21 20 34" src="https://github.com/ngocle2497/BoilerplateReactNative/assets/17426288/8339871d-1000-4bc3-a5b3-2b0702ac5343">
@ngocle2497 sr, this is end of logs

**Comment by ngocle2497** [comment]
check your .xcode.env.local  file to verify node path

**Comment by kentdev92** [comment]
Just checked it, and after that it show another error about hermes:


> check your .xcode.env.local file to verify node path

Thank you. Right after manual change node path inside ios/.xcode.env.local to my current node path, it's working

**Comment by phanvungoc96** [comment]
Mình sửa lại node trong file đó rồi mà vẫn bị
ios/.xcode.env.local
export NODE_BINARY=/Users/xxx/.nvm/versions/node/v18.20.2/bin/node
