### ISSUE TITLE
Error code 127 exist right after setup project

### ISSUE THREAD

**Issue by phanvungoc96** [hngocl/BoilerplateReactNative#36]
Mình có setup lại như hướng dẫn và chỉnh node trong file xcode.env.local nhưng vẫn bị lỗi
node nvm 18.20.2

**Comment by ngocle2497** [comment]
> Mình có setup lại như hướng dẫn và chỉnh node trong file xcode.env.local nhưng vẫn bị lỗi
> 
> node nvm 18.20.2

Nếu bạn có dùng homebrew, hãy thêm 
PATH="/otp/hombrew/bin:$PATH"
Vào dòng trên cùng của pre-action(xcode > edit scheme > build > Pre-actions)
Lỗi này do xcode không nhận node của hệ thống. Nên cần phải cập nhật path cho xcode
Nếu run bằng cmd thì không cần

**Comment by ngocle2497** [comment]
Fixed in  [1.72.38](https://github.com/ngocle2497/BoilerplateReactNative/releases/tag/1.72.38)
